Commonjava/indy-generic-proxy-service

- src/main/java/org/commonjava/indy/service/httprox/HttpProxy.java
- src/main/java/org/commonjava/indy/service/httprox/client/content/ContentRetrievalService.java
- src/main/java/org/commonjava/indy/service/httprox/client/repository/Transfer.java
- src/main/java/org/commonjava/indy/service/httprox/config/ProxyConfiguration.java
- src/main/java/org/commonjava/indy/service/httprox/handler/ProxyAcceptHandler.java
- src/main/java/org/commonjava/indy/service/httprox/handler/ProxyResponseWriter.java
- src/main/java/org/commonjava/indy/service/httprox/handler/TransferStreamingOutput.java
- src/main/java/org/commonjava/indy/service/httprox/util/HttpConduitWrapper.java
- src/main/java/org/commonjava/indy/service/httprox/util/ProxyResponseHelper.java
- src/test/java/org/commonjava/service/httprox/HttpProxyTest.java
- src/test/java/org/commonjava/service/httprox/client/ContentRetrievalServiceTest.java
- src/test/java/org/commonjava/service/httprox/client/mock/MockableContentRetrievalService.java
- src/test/java/org/commonjava/service/httprox/client/mock/MockableRepositoryService.java
- src/test/resources/application.properties
- src/test/resources/simple.pom
For retrieving the artifacts, generic proxy service needs to access indy REST first and then stream the result back, the pr I try to use the `PipedOutputStream` in `ProxyResponseHelper` to transit it from Indy response to client. Not sure if this is right, please help to review. And there are two tests in `HttpProxyTest` for it.
> Init tests for httprox

- pom.xml
- src/main/java/org/commonjava/indy/service/httprox/handler/ProxyAcceptHandler.java
- src/main/java/org/commonjava/indy/service/httprox/handler/ProxyResponseWriter.java
- src/main/java/org/commonjava/indy/service/httprox/util/CacheProducer.java
- src/main/java/org/commonjava/indy/service/httprox/util/ProxyResponseHelper.java
When I grabbed one builds from production, found the case that one build request hundreds of generic request, that means it will request to check the same store frequently, the PR added the in-momery cache for the store to avoid the loads to main indy.
> Cache store to avoid the loads to main indy

- src/main/java/org/commonjava/indy/service/httprox/util/ProxyResponseHelper.java
Fix the thing caught on stage:
`WARNING [okh.OkHttpClient] (OkHttp ConnectionPool) A connection to <> was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE:`
> Fix the connection leak

- src/main/java/org/commonjava/indy/service/httprox/util/ProxyResponseHelper.java
Checked from the logs, this should be synced in case the parallel requests for querying/creating the same repository.
> Sync the method for querying the repository

- src/main/java/org/commonjava/indy/service/httprox/handler/ProxyMITMSSLServer.java
- src/main/java/org/commonjava/indy/service/httprox/util/HttpConduitWrapper.java
When the timeout happens, it should close the connection rather than handling the exception, throwing exception and handling it later cause it hangs on the client(builder tool), ref MMENG-3127.
> Close the connection when exception happens

- src/main/java/org/commonjava/indy/service/httprox/client/content/ContentRetrievalService.java
Let's rollback this redirection since it does not work for some cases. 
This reverts commit 70f36ca76f9a48c0050b9b6e78144620ae40648b.
> Revert "redirect to the default page if path is null"

- src/main/java/org/commonjava/indy/service/httprox/handler/ProxyResponseWriter.java
Fix the format of the header according to https://www.rfc-editor.org/rfc/rfc2616
which is the root cause that why `npm install` does not sent get request after connection established.
> Fix the format of the header

- Jenkinsfile
- src/main/java/org/commonjava/indy/service/httprox/handler/AbstractProxyRepositoryCreator.java
- src/main/java/org/commonjava/indy/service/httprox/handler/ProxyMITMSSLServer.java
- src/main/java/org/commonjava/indy/service/httprox/handler/ProxyResponseWriter.java
- src/main/java/org/commonjava/indy/service/httprox/util/ProxyResponseHelper.java
- src/main/java/org/commonjava/indy/service/httprox/util/UrlUtils.java
- src/main/resources/application.yaml
- src/test/java/org/commonjava/service/httprox/AbstractGenericProxyTest.java
- src/test/java/org/commonjava/service/httprox/HttpProxyTest.java
- src/test/java/org/commonjava/service/httprox/ProxyHttpsTest.java
- src/test/resources/simple-2.0.pom
This is for [MMENG-3880](https://issues.redhat.com/browse/MMENG-3880) - Take query string into account when downloading through generic proxy.
It encodes query parameters in remote urls by safe base64 before sending request to content service. This is one part of the whole picture. The other part is on main Indy (content service). The content service needs to recognize the encoded url and decode it before sending request to remote site.
I will hold this pr until the other part is ready. Meanwhile, this pr is ready for review.
> Use base64 to take query string into encoded path

- src/main/java/org/commonjava/indy/service/httprox/handler/AbstractProxyRepositoryCreator.java
- src/main/java/org/commonjava/indy/service/httprox/util/UrlUtils.java
- src/test/java/org/commonjava/service/httprox/AbstractGenericProxyTest.java
The prev pr only encoded paths with query parameters. But that was not nice because it confused us as whether a proxy created repo is encoded or not. This fix treat all proxy generated repo as base64 encoded.
> Encode all path whether or not hasQueryParam

- src/main/java/org/commonjava/indy/service/httprox/util/ProxyResponseHelper.java
Last week there was a stuck happening in generic proxy on production, I checked the logs and cannot find the cause for it. Adding this for tracking the request for store info and hope we can grab more info in next time.
> Add logger for tracking the store response

- src/main/java/org/commonjava/indy/service/httprox/config/ProxyConfiguration.java
- src/main/java/org/commonjava/indy/service/httprox/handler/AbstractProxyRepositoryCreator.java
- src/main/java/org/commonjava/indy/service/httprox/handler/ProxyAcceptHandler.java
- src/main/java/org/commonjava/indy/service/httprox/util/RepoCreator.java
- src/main/resources/application.yaml
The new enum value 'base64url' breaks pnc client, as in [NCL-8287](https://issues.redhat.com/browse/NCL-8287). I add a config for it. For backward compatible, default is 'hashed'.
We can switch to new value only after PNC has updated the dependency.
> Add config storage.path.style and default to hashed

- pom.xml
- src/main/java/org/commonjava/indy/service/httprox/util/LockWrapper.java
- src/main/java/org/commonjava/indy/service/httprox/util/ProxyResponseHelper.java
After testing locally, I suspect this part may cause the stuck somehow, and let's use the way `lockByKey` to avoid to block all the executor here, since it's no sense to block two if they are different requests.
> Refine the locker against the funtion getArtifactStore

- src/main/java/org/commonjava/indy/service/httprox/HttpProxy.java
- src/main/java/org/commonjava/indy/service/httprox/config/ProxyConfiguration.java
- src/main/resources/application.yaml
After test locally I found that this configuration can control the incoming connections to our proxy server, to avoid the cases that some npm/yarn builds triggered lots of the request at the very same time, which may cause the stuck in the proxy server due to the exhaustion of resources. for example the following part of the logs I grabbed for the build:
https://privatebin.corp.redhat.com/?3540fffd9e3fa72e#Fh2EKSjHzbRK26d5XvQStVpFdDDprnwvnum9fqSek2oS
This will be useful especially we have fewer resources than before in indy monolith.
> Add the setting to control the connections

- pom.xml
The quay.io report a new Critical after updating to org.keycloak:keycloak-core:8.0.2. As it suggested, I update it again to 13.0.0.
> Update keycloakVersion to 13.0.0

- src/main/java/org/commonjava/indy/service/httprox/util/ProxyResponseHelper.java
- src/main/java/org/commonjava/indy/service/httprox/util/RepoCreator.java
Fix for MMENG-3973:
- the artifacts which are backed up in the hosted repo should be reused afterwards, to support rebuilding. 
- this PR adjusts the order of the constituents of the group, having the hosted repo as the first constituent and the remote one as the second.
- only the request with suffix `+tracking` will be tracked
> Fix the tracking logic

- src/main/java/org/commonjava/indy/service/httprox/handler/ProxySSLTunnel.java
- src/main/java/org/commonjava/indy/service/httprox/util/ChannelUtils.java
Checking the latest logs on prod, I found that the infinite loop happens somehow, even though there is a timeout setting (5mins) to break the loop, but still causing the timeout from the client. We should make it retry and fail the request earlier.
> Fix the infinite loop issue when writing to channel

- src/main/java/org/commonjava/indy/service/httprox/config/ProxyConfiguration.java
- src/main/java/org/commonjava/indy/service/httprox/handler/ProxyAcceptHandler.java
- src/main/java/org/commonjava/indy/service/httprox/handler/ProxyMITMSSLServer.java
- src/main/java/org/commonjava/indy/service/httprox/handler/ProxyRequestReader.java
- src/main/java/org/commonjava/indy/service/httprox/handler/ProxyResponseWriter.java
- src/main/java/org/commonjava/indy/service/httprox/util/HttpConduitWrapper.java
This is for [MMENG-4106](https://issues.redhat.com/browse/MMENG-4106). 
Add method 'closeProperly' to handle all uncaught exceptions and close the channels if necessary. Some other fixes are added to make sure all the sock or streams are closed after the try/catch, and fail fast when timeout.
> Properly close channels after MIMT server completed

- src/main/java/org/commonjava/indy/service/httprox/util/HttpConduitWrapper.java
Fix for MMENG-4165, there are issues with incomplete downloads and failures when using curl/wget on prod. It maybe caused by missing both `Content-Length` and `Transfer-Encoding`. For some binary files, if there is no content-length from the original response header, we need to return the Transfer-Encoding then.
> Add the header Transfer-Encoding into response

- src/main/java/org/commonjava/indy/service/httprox/util/HttpConduitWrapper.java
Reverts Commonjava/indy-generic-proxy-service#94 since this may need corresponding chunked data format. Will check further to see how to fix it.
> Revert "Add the header Transfer-Encoding into response"

- src/main/java/org/commonjava/indy/service/httprox/util/ProxyResponseHelper.java
Close the okhttp3 response object when below error happens. This may have caused the WAIT_CLOSE socket.
2024-07-08 09:32:06,556 ERROR [or.co.in.se.ht.ut.ProxyResponseHelper] (OkHttp http://indy-gateway.indy.svc.cluster.local/...) write transfer error: Connection reset by peer (Write failed): java.net.SocketException: Connection reset by peer (Write failed)
...        
at java.base/java.io.FilterOutputStream.write(FilterOutputStream.java:108)
at org.commonjava.indy.service.httprox.util.OutputStreamSinkChannel.write(OutputStreamSinkChannel.java:165)
at org.commonjava.indy.service.httprox.util.ChannelUtils.write(ChannelUtils.java:53)
at org.commonjava.indy.service.httprox.util.HttpConduitWrapper.writeExistingTransfer(HttpConduitWrapper.java:134)
at …
> Close response when write transfer error

- src/main/java/org/commonjava/indy/service/httprox/util/HttpConduitWrapper.java
Fix for MMENG-4165, there are issues with incomplete downloads and failures when using curl/wget on prod. 
After checking, it's caused by that it response with chunked way but wrong format in body, this adds the support for that based on the doc: https://www.rfc-editor.org/rfc/rfc9112#field.transfer-encoding
I test it with wget and curl in both ubi7 & ubi8, works well and will test it on dev later.
> Update to support chunked transfer

- src/main/java/org/commonjava/indy/service/httprox/handler/ProxyMITMSSLServer.java
- src/main/java/org/commonjava/indy/service/httprox/handler/ProxyResponseWriter.java
- src/main/java/org/commonjava/indy/service/httprox/handler/ProxySSLTunnel.java
This can be reproduced via running curl on ubi7, ref MMENG-4165 for the steps,  that the proxy server closed but there are still remaining bytes in SSL tunnel.
> Add check for SSL tunnel before closing proxy server

- pom.xml
- src/main/java/org/commonjava/indy/service/httprox/util/CacheProducer.java
- src/main/java/org/commonjava/indy/service/httprox/util/ProxyResponseHelper.java
We plan to integrate this as a sidecar to the mw pipeline, and have to slim the image to avoid the performance issue when download the image each time for mw pipeline running.  We can do this from app level and image level, this PR is for app level, I found two big deps, one is quarkus-opentelemetry and another one is infinispan.
> Replace infinispan with the lightweight caffeine
